name: Commandspy
main: net.korikisulda.commandspy3.Main
version: 3.1.1
author: korikisulda
description: Spy on your users. In style.
commands:
    commandspy:
      description: Access commandspy subcommands
      usage: /commandspy help
      aliases: [c, cs,cspy,kosu]
softdepend: [WorldEdit]
